### PR TITLE
Increase size of xref column

### PR DESCRIPTION
**Pull request by Herkemer**
Generally headers are allowed to be 988 octets, so I believe 256 was too small for this column.  I was seeing lots of errors when trying to insert.

This is my first shot at alembic so please double check that I didn't screw up anything.

### CODE REVIEW

**Comment by Murodese** [comment]
I think the lengths on your type/existing_type in upgrade() are backwards? Think it should be existing_type=sa.VARCHAR(length=256), type=sa.String(length=1024).

Thanks, I checked the NNTP standards looking for length limits and didn't find a whole lot so I guessed most of them.

**Comment by Murodese** [comment]
You can check and see what's going to be done by doing: `alembic upgrade head --sql > migration.sql`, which'll generate a migration sql script that you can check manually.

**Comment by Herkemer** [comment]
Oops, I mean 998 octets.  Here is the reference: http://tools.ietf.org/html/rfc5536#section-2.2

Fixed the reversed SQL.  I did it with alembic revision --autogenerate on an already changed DB, guess that wasn't quite right.

Thanks.

**Comment by Murodese** [comment]
Yeah, generally speaking the workflow is to write the changes into db.py and use alembic autogenerate/upgrade to change your db, rather than modifying the db yourself.

**Pull request merged**
