### PR TITLE
Monitoring enhancements

### PR DESCRIPTION
**Pull request by AlanKK**
This is my checkin for https://github.com/Murodese/pynab/issues/141.

Changes:
- Use byobu instead of teamocil
- Condensed logging format
- Replaced monitor.sh with a tmux version with two windows (use alt-left/right to select)
- Knocked common log messages down to debug

I recommend changing the default logging level to INFO in config_sample.py.

### CODE REVIEW

**Comment by Murodese** [comment]
Cool! Thanks for the hard work :) I'll have to manually merge some of it, since there's been some other bugfixes since.

**Comment by AlanKK** [comment]
I just pushed another small change, replacing scan.log with pubsub.log

**Comment by Murodese** [comment]
Additionally, it works ok without byobu installed but dies after I've installed it. Byobu 5.74.

```
session not found: 1
(something I can't read quickly enough before it disappears)
session not found: 2
```

Then just the stats.py window will come up.

**Comment by Murodese** [comment]
Oh wait, now it's doing it with tmux too. Maybe it's not cleaning up the tmux sessions properly if it's exited?

**Comment by AlanKK** [comment]
Hmm.  How are you exiting?

**Comment by Murodese** [comment]
Just control-c.

**Comment by AlanKK** [comment]
try ./monitor.sh 2> mon.log to capture errors

**Comment by AlanKK** [comment]
tmux kill-session will clean everything up.  It shouldn't be needed if you are using ctrl-c to kill all panes in both windows.

**Comment by Murodese** [comment]
Just `session not found: 2`.

**Comment by Murodese** [comment]
`james@indexer:/opt/pynab$ tmux kill-session 
failed to connect to server`

:v

**Comment by AlanKK** [comment]
It is probably not finding one of the logs.  You might not have a scan.log?  I changed that to pubsub.log in the last checkin after realizing scan.log hadn't updated in a while.

**Comment by Murodese** [comment]
scan.log became update.log.

**Comment by AlanKK** [comment]
> tmux kill-session failed to connect to server

That just means tmux is not running.

**Comment by Murodese** [comment]
Yeah, even after changing scan.log to pubsub.log it's coming up with the same stuff. Stats window loads, rest don't.

**Comment by AlanKK** [comment]
ok.  I'll test it with a clean install.

**Comment by AlanKK** [comment]
It may not be parsing config.py to find the logging_dir.  Can you run these and let me know what it thinks logging_dir is?

SCRIPT_PATH=$( readlink -m $( type -p $0 ))      
SCRIPT_DIR=$( dirname ${SCRIPT_PATH} )       
LOGGING_DIR=$( grep logging_dir $SCRIPT_DIR/config.py | awk -F\' '{print $4 }' )
echo $LOGGING_DIR

**Comment by AlanKK** [comment]
ah, these need to be in a simple script that you run.

**Comment by Murodese** [comment]
```
james@indexer:/opt/pynab$ ./test.sh
/opt/pynab/test.sh
/opt/pynab
/var/log/pynab
```

Seems correct.

**Comment by AlanKK** [comment]
Ok.  I'll do some more testing

**Comment by Murodese** [comment]
Weird that it worked the first time, just not the others. There's nothing obviously still running, either.

The only change I made to the script was to change `tail -f`'s to `tail -F`, which is needed for logrotated files.

**Comment by Murodese** [comment]
Huh, actually, that was the problem. `tail -F` causes it all to break, but we need `-F` :v

**Comment by AlanKK** [comment]
That doesn't break it for me

**Comment by Murodese** [comment]
Yeah, changing one or two tail lines to -F will break those specific windows. Hrm.

**Comment by Murodese** [comment]
Copying out the path sets from the script and one of the tail lines doesn't bring up any problems with the tail, though. Works fine.

~~ugh~~

**Comment by AlanKK** [comment]
I don't understand what you mean

**Comment by Murodese** [comment]
ie. having a script that contains:

```
SCRIPT_PATH=$( readlink -m $( type -p $0 ))
SCRIPT_DIR=$( dirname ${SCRIPT_PATH} )
LOGGING_DIR=$( grep logging_dir $SCRIPT_DIR/config.py | awk -F\' '{print $4 }' )

tail -F $LOGGING_DIR/update.log
```

Brings up a tail that works fine, so it's no obvious error.

When you start the monitor, do you get these warnings in every windowpane?: `tail: warning: following standard input indefinitely is ineffective`

**Comment by AlanKK** [comment]
No, I don't get that. error.  What linux distro are you using?

**Comment by Murodese** [comment]
Ubuntu 14.04.

**Comment by AlanKK** [comment]
Same here.  I also have tmux 1.8 (tmux -V).

**Comment by Murodese** [comment]
Likewise. Tail 8.21?

**Comment by AlanKK** [comment]
Same.

$ tail --version
tail (GNU coreutils) 8.21

**Comment by AlanKK** [comment]
Hmmm...

http://bugfix.ooz.ie/2010/11/tail-warning-following-standard-input.html

**Comment by Murodese** [comment]
Running the commands manually, ie. `echo 'ERROR|CRITICAL errors from all logs' ; tail -F /var/log/pynab/*.log  | egrep "ERROR|CRITICAL"` works fine, too.

Bizarre.

Also yeah, saw that link. The error message itself is some kind of joke - not that helpful, currently.

**Comment by Murodese** [comment]
Hooo, actually, check this:

```
james@indexer:/opt/pynab$ tail -f
tail: warning: following standard input indefinitely is ineffective
^C
james@indexer:/opt/pynab$ tail -F
tail: cannot follow ‘-’ by name
```

This seems to imply that tail isn't receiving arguments properly - since -f means nothing was passed, and -F means it fails entirely - which it does, in both cases.

**Comment by Murodese** [comment]
Found the problem:

```
SCRIPT_PATH=$( readlink -m $( type -p $0 ))
SCRIPT_DIR=$( dirname ${SCRIPT_PATH} )
LOGGING_DIR=$( grep logging_dir $SCRIPT_DIR/config.py | awk -F\' '{print $4 }' )

echo "tail -F $LOGGING_DIR/update.log"
```

```
james@indexer:/opt/pynab$ ./test.sh
tail -F
/var/log/pynab/update.log
```

It's adding a newline.

**Comment by AlanKK** [comment]
Yeah.  just found this in the tail source code:

    /* When following forever, warn if any file is '-'.
       This is only a warning, since tail's output (before a failing seek,
       and that from any non-stdin files) might still be useful.  */
    if (forever && found_hyphen && isatty (STDIN_FILENO))
      error (0, 0, _("warning: following standard input"
                     " indefinitely is ineffective"));

**Comment by Murodese** [comment]
Pretty sure it's adding a newline at the start of /var/log/pynab, rather than the end of tail -F.

**Comment by AlanKK** [comment]
I think you are right but I am not seeing it when I experiment on the command line

**Comment by Murodese** [comment]
Can you paste the relevant section of your config.py?

**Comment by AlanKK** [comment]
log = {
    # logging settings
    # ----------------
    # logging_file: a filepath or None to go to stdout
    # this should be something like '/var/log/pynab/pynab.log'
    # it'll automatically split the logfiles for you
    'logging_dir': '/var/log/pynab',

    # logging.x where DEBUG, INFO, WARNING, ERROR, etc
    # generally, debug if something goes wrong, info for normal usage
    'logging_level': logging.INFO,

    # max_log_size: maximum size of logfiles before they get rotated
    # number, in bytes (this is 50mb)
    'max_log_size': 50*1024*1024,
        
    # enable/disable color logging to console
    'colors': 'True',
}

**Comment by AlanKK** [comment]
still trying to figure out github code formatting in these comments

**Comment by Murodese** [comment]
Single lines: between backticks ie `lol`
Multiple: between three backticks each side, ie.
```
lol
```

**Comment by AlanKK** [comment]
fixed :-)

**Comment by Murodese** [comment]
Haha, I see why.

You're using an older config that you've copied stuff to, which is why it's not happening for you. Grepping `logging_dir` from your config.py only returns one line - the variable. Doing it on mine (a fresh copy) returns two lines: the description line, and then the second line. So, it's grabbing a newline first and then the config and putting the two together:

```
james@indexer:/opt/pynab$ grep logging_dir /opt/pynab/config.py
    # logging_dir: a filepath or None to go to stdout
    'logging_dir': '/var/log/pynab',
```

Changing it to:

```
james@indexer:/opt/pynab$ grep \'logging_dir\' /opt/pynab/config.py
    'logging_dir': '/var/log/pynab',
```
Works fine, as seen.

**Comment by Murodese** [comment]
Works now :) Fixed in 7f7f564287751cab0e8f713825349b9728ba93d0.

**Comment by AlanKK** [comment]
oh, shit.  Sorry and thanks.

**Comment by Murodese** [comment]
Haha, no problem. Just tricky to track down :)

**Comment by AlanKK** [comment]
A better solution for changes to config.py is needed but I don't know what it is.  Seems like I am constantly merging by hand.

**Comment by Murodese** [comment]
I was thinking about that the other day and implemented a partial start on it as `pynab/__init__.py:check_config()`, which can identify missing config sections. Shouldn't be too hard to expand that into autogenerating missing sections, but I don't have time at the moment. Either way, wouldn't've helped here - it was in a comment :v

**Comment by AlanKK** [comment]
Also, if you want any changes in how the windows and panes are laid out, let me know.  It is currently laid out based on my current personal preference.  I have a pretty good understanding of tmux config now and can change it quickly.

**Comment by AlanKK** [comment]
I thought I would make a change to start and stop stats.py along with everything else in pynab.py instead of in monitor.sh.  It would write to a log file that we'd tail in monitor.sh.  That way, we'd collect stats always when we run.  What do you think?

**Comment by Murodese** [comment]
Sounds good. I'm also going to add the prebot to the normal start routine I think.

**Pull request merged**
