### PR TITLE
Look for library in the right place

### PR DESCRIPTION
**Pull request by Herkemer**
Looks like with the lib path properly set this is actually looking for the files in scripts in the wrong place.

### CODE REVIEW

**Comment by brookesy2** [comment]
Thanks for that :) My bad!

**Comment by Herkemer** [comment]
Another small change, keep the processNzedbPre function from running on import since during install.py the tables aren't yet created.

**Comment by brookesy2** [comment]
Ahh thats odd. I thought @Murodese recommended me to do it, maybe I heard it wrong :) Sorry!

**Comment by Murodese** [comment]
On import, not on install. You'll see at the bottom of most of my scripts (and the change that @Herkemer made) a line that looks like `if __name__ == '__main__':`. This guard prevents code from being executed if the file is imported by another script, so you can still use any functions/classes defined by the file but without any code automatically being run unless the file is executed directly. Basically, when install.py hit the `import scripts/nzedb_import..` line, it'd load the module and immediately execute processNzedbPre(), which would fail because the tables don't exist. 

Thanks for the fix, @Herkemer :)

**Comment by brookesy2** [comment]
Awesome! Annoyingly I am aware of the __main__ thing, just didn't cotton on
:(

**Comment by brookesy2** [comment]
Also thanks @Herkemer :)

**Pull request merged**
