### PR TITLE
Pre import added to install.py

### PR DESCRIPTION
**Pull request by brookesy2**
I am gonna be honest here, I didn't actually test this, but its pretty low risk.. Famous last words.

### CODE REVIEW

**Comment by Murodese** [comment]
That's what dev branches are for: living on the edge.

**Comment by brookesy2** [comment]
You are one crazy mofo!!!

**Comment by ajoergensen** [comment]
Are there any plan to include the big predb dump? (https://www.dropbox.com/s/btr42dtzzyu3hh3/predb_dump-062714.csv.gz)

**Comment by brookesy2** [comment]
I will have a look at that file this weekend. It may just be a combined
version of what the importer does now.

Technically the importer could be modified to accept a command line
argument to import a specific file.

At the moment it just goes over every existing file on the nzedb Dropbox.

**Comment by ajoergensen** [comment]
The small files are daily "dumps" beginning at the date where the big one ends.

**Comment by brookesy2** [comment]
Amazing!! On my phone at the moment, but when I can see the file I will
look in to a path on what to do. My issue is I don't want people trying to
import it more than once! I only store what files have been imported in a
local text file, which can obviously be deleted easily.

Best bet will be to process it through install.py. Which means I will
probably just add another function to specifically deal with the large
file.

Thanks for bringing this up!!

**Comment by Murodese** [comment]
Do that so I can get rid of some more of my 8010 releases :tada:

**Comment by brookesy2** [comment]
@Murodese  Fuck me, this thing is 302MB compressed lol. Going to need to brush up on some lazy loading to ever have a hope of processing this! Hopefully can work it out over the weekend.

**Comment by Murodese** [comment]
open() yields a generator, so `for line in open('somefile.csv')` will use minimal memory. You'll just need to extract the file out-of-memory first.

**Comment by brookesy2** [comment]
The issue is the amount of processing I have to do to squeeze it into our tables. Not to mention the query to detect duplicates within the DB will continue to get larger!

But yeah, not gonna try process it as a gz :p Either way, good time to learn something new!

**Comment by brookesy2** [comment]
And if my brain can't learn it, I will just split it into a lot of smaller files! The cowards way out :p

**Comment by Murodese** [comment]
What I'd probably do is pull in an amount of data (maybe 20-50k lines), check if they exist already, then COPY it in. Also (I just noticed), you should rework your current script to use the copy function in pynab/db.py, since that handles postgres+mysql (COPY isn't standard). Should be minimal change necessary to support that.

**Comment by brookesy2** [comment]
Thanks mate! I will give it a whirl at least. Can't promise it will be quick! 

I also noticed that function in db.py, so I will attempt to make that change also!

**Comment by Murodese** [comment]
I think the generic copy function I wrote takes identical parameters to the postgres one, so it should just be a matter of changing the function call and stripping the other stuff out (getting the connection etc).

**Comment by brookesy2** [comment]
@Murodese Yeah, already made that change. I will make a PR for that first before attempting the larger import :)

**Comment by brookesy2** [comment]
While doing this I have found the original import isn't perfect, can't figure out exactly why though, but if you run it multiple times it seems to do crazy shit to the db. I think I have a path for the big file though, so that is good news. Converted everything to pandas, no more crazy os.system :)

**Pull request merged**
