### PR TITLE
convert_from_newznab rework and bug fixes.

### PR DESCRIPTION
**Pull request by Herkemer**
This has the potential to be a little bit controversial.  From the looks of it the cymysql module and the mysql config portion of the config.py file are used only for the convert_from_newznab.py script.  This change removes those aspects and makes convert_from_newznab.py a little more standalone.

You now simply supply the MySQL config options via command line and only need to install the cymysql module if you are indeed converting.  Otherwise you need not worry about it at all.

This also fixed a couple of small bugs in the conversion from when the database tables for movies was updated.

### CODE REVIEW

**Comment by Murodese** [comment]
Wanna go the whole way and change it to use pymysql, since that's what we're using for mysql support now anyway? :p

**Comment by Herkemer** [comment]
Actually, I could do that, let me give it a go.

**Comment by Herkemer** [comment]
Ended up being much easier than I suspected, yay for compatible APIs.  Also updated the README file.

**Comment by Murodese** [comment]
Yeah, they all work off the same API. The note you removed about getting rid of duplicate fields in imdb/tvrage tables - toss that in the README. If that's not done first, the whole process will fail (probably? It's been a while since I tested it).

**Comment by Herkemer** [comment]
I removed it because there is actually a dupe check in the script, it looks up the tvshow or movie first and will insert only if it's not found.

**Comment by Murodese** [comment]
Ah, no worries.

**Comment by Murodese** [comment]
Good set of changes and it all looks fine, thanks for the hard work :)

**Pull request merged**
