### PR TITLE
Prebot

### PR DESCRIPTION
**Pull request by brookesy2**
Here is the prebot code and the function to scrape orlydb. I will attempt to build this in to the existing post process.

For whatever reason I could just NOT rebase my old fork, it really didn't want to ditch that odd commit. So I just reforked and started over. Sorry for the confusion last time!

### CODE REVIEW

**Comment by brookesy2** [comment]
I should probably have added the irc library to requirements.txt :(

**Comment by Murodese** [comment]
Always happens, don't worry about it :) I'll add it in when I get there.

Just doing #121 at the moment.

**Comment by brookesy2** [comment]
No rush, legendary work as usual :)

**Comment by Murodese** [comment]
Had to fix the alembic scripts a bit, since you were missing one :)

Generally speaking, if you're adding a model (like Pre) you do this:

1) Add model to `pynab/db.py`
2) Run `alembic revision --autogenerate -m "add pre entity"
3) Run `alembic upgrade head`
4) Make any necessary changes to model (adding a unique, or whatever)
5) Repeat 2-4
6) Commit all alembic versions

You may have done that, but you missed the very first revision that actually created the table, so the others all failed :) Not to worry, fixed now.

**Comment by brookesy2** [comment]
Awesome! Thanks mate :) knew I wouldn't get that alembic stuff right!!

Overall it ran fairly stable, it managed 13900 pre's before it needed a
restart. Trying to figure out why!

**Comment by brookesy2** [comment]
Err we may have had an issue on this one. Did you rename the pre table pres? It should have been named that originally, but I believe I messed up and you may have updated it (if not 100% my fault!). Anyway it had a knock on effect in that the definition in db.py was incorrect.

```python
    pre_id = Column(Integer, ForeignKey('pre.id'), index=True)
    pre = relationship('Pre', backref=backref('pre'))
```

Needs to be, I believe?:

```python
    pre_id = Column(Integer, ForeignKey('pres.id'), index=True)
    pre = relationship('Pre', backref=backref('pres'))
```

I also noticed another issue I forgot to, CREATE SEQUENCE pres_id_seq; , as during testing I just used the parts sequence, bad me!!

I can create a pull request to fix the pre stuff, unsure how I make one for the sequence update?

**Comment by Murodese** [comment]
A new alembic revision that creates the sequence and then assigns it to the key that was using it :)

**Comment by brookesy2** [comment]
Ok, just tested. Seems I only need to make a pull request for db.py and we should be good. Will do that now.

**Comment by Murodese** [comment]
Nevermind, I just fixed it anyway - had to because it was breaking other db ops.

**Comment by Murodese** [comment]
I didn't touch the sequence though!

**Comment by brookesy2** [comment]
Ok, weird, as on my main install the pres sequence added fine. What is more odd is that only a few columns ended up making it into alembic. The below is what was specified when I autogenerated, yet only half the columns are in the pres table?

Sorry for getting us into this mess :(

```python
class Pre(Base):

    __tablename__ = 'pres'

    id = Column(BigInteger, primary_key=True)

    pretime = Column(DateTime)
    name = Column(String, index=True)
    searchname = Column(String)
    category = Column(String)
    source = Column(String)
    requestid = Column(BigInteger)
    requestgroup = Column(String)
    filename = Column(String)
    nuked = Column(Boolean, default=False)

    __table_args__ = (UniqueConstraint(name),)
```

**Comment by Murodese** [comment]
The alembic revision in git was written by me by hand, because there was no creation at all to begin with. To re-sync alembic, what you'll probably need to do is delete the table, let it recreate it as part of the alembic upgrade and then re-run autogenerate to add the extra columns.

Not to worry, alembic can sometimes bust up. It won't add certain changes sometimes as well - generally, you generate the revision and check over it manually. If anything's missing, you add it to the revision manually.

**Comment by brookesy2** [comment]
I will do that now.

I think I need to get some training wheels :)

**Pull request merged**
