### PR TITLE
Scripts to backup/restore database data and export release nzb files

### PR DESCRIPTION
**Pull request by Herkemer**
This is just a basic script to export saved nzb files for releases.

### CODE REVIEW

**Comment by Murodese** [comment]
I'm slowly migrating everything over to docopt, mind if you change it for this one? There's an example in pynab.py, and lots of docs here: http://docopt.org/

**Comment by Herkemer** [comment]
Switched to docopt.

**Comment by Herkemer** [comment]
Updated to include backup/restore scripts for critical data.

**Comment by Herkemer** [comment]
Should fix Issue #143

**Comment by Murodese** [comment]
The change to server.py will break stuff at random. The... garbage NNTP port of death? bug will cause that to crash the whole script, because it'll try to print random non-unicode data to the logger. You might want to change it instead to just print out the class name of the exception, ie. NNTPDataError, instead of the data within it as well.

**Comment by Herkemer** [comment]
I added that debug while trying to figure out why my NNTP stuff kept failing and ended up just leaving it in for the last week or so.

I just reverted it, it's not really needed and never really helped.

**Comment by Murodese** [comment]
Great. Thanks for the hard work, much appreciated.

**Pull request merged**
