### PR TITLE
Add ability for Post Proc to match requests from the Pre table

### PR DESCRIPTION
**Pull request by brookesy2**
Changes:

* Added requests.py to deal with finding requests from release table and finding associated pres
* Modified postprocess.py to utilize requests.py
* Modified releases.py to utilize requests.py
* Modified rename_bad_releases.py so that it would find releases with a pre attached
* Added a setting to config_sample.py that allows for request checking

One thing I noticed is that postprocess.py/rename_bad_releases.py don't change the name of the release, just the search name. Is that normal? Also unwanted is set to true?

The processing was done in a bulk manner, I am unsure on the performance of a query in a for loop. (In regards to my other comment). Happy to change it as readability would be easier if it was.

### CODE REVIEW

**Comment by Murodese** [comment]
Do me a favour and do a git pull so I don't have to manually merge it :)

The name/search_name thing was intentional, but I think the added pain from having a weird name / normal searchname outweighs any benefit, so I might change that. Unwanted is intentionally set to true if we can't find a good name.

**Comment by brookesy2** [comment]
Done. A few file permissions changed though. Want me to correct them?

**Comment by Murodese** [comment]
Yeah.

**Comment by brookesy2** [comment]
Should be good now. Only one I am unsure on is postprocess, is it 755 by default or 644?

**Comment by Murodese** [comment]
755 for that.

**Comment by brookesy2** [comment]
Done :)

**Comment by Murodese** [comment]
Got it, thanks :)

**Comment by brookesy2** [comment]
@Murodese So after this PR my load averages when post processing are WAY higher. Do you think anything I added was woefully inefficient? Or maybe has issues with any other changes after this?

**Comment by Murodese** [comment]
I can't see any real issues. Could be because unwanted releases aren't being deleted and it's running discover_name over them every iteration.

**Comment by brookesy2** [comment]
Let's see if anyone else runs into it. It brings my machine to its knees!!

**Comment by Murodese** [comment]
Is this during the postproc section (when rar/nfo/pre etc are doing their thing) or later on, during name discovery?

**Comment by brookesy2** [comment]
I went to bed so haven't tested much. But tonight after work I will comment
some stuff out and see where speed improves.

**Comment by brookesy2** [comment]
@Murodese So I am pretty certain it is my code. If I comment out:

```python
if config.postprocess.get('process_requests', True):
    threads.append(executor.submit(process_requests))
```
Load averages - load average: 0.62, 0.45, 0.42

With it uncommented - load average: 8.23, 3.29, 1.44 (continues to get higher)

Obviously they are point in time, but hover around there.

Could the in_ operator be inefficient?

**Comment by Murodese** [comment]
Naw, I use it in a lot of places, including spots where it takes large lists (`pynab/binaries.py:212`).

**Comment by Murodese** [comment]
I stepped through it and can't really see why it'd be using so many resources. My preDB is not very big though - did you do an import or a large dump or something? Toss it to me and I'll test it with that enabled.

**Comment by brookesy2** [comment]
Weird. Fairly large, but not crazy. 27k rows?

https://drive.google.com/file/d/0B16YG3BLQPQ3eENCRml4Z2VRSE0/view?usp=sharing

**Comment by Murodese** [comment]
Well, you were missing indexes on the two main fields that would've been slowing it down massively, but the CPU usage should've been reported by postgres, not python.

**Comment by brookesy2** [comment]
Ha! That is hilariously bad of me. First thing I should have though of! Let me slap on some indexes and try.

**Comment by Murodese** [comment]
Already did, just do an update.

**Comment by brookesy2** [comment]
Legend! I'm glad you maintain this and not me! lol (as I am sure all the other users are!)

**Comment by Murodese** [comment]
```
2015-01-30 15:21:07 INFO  Requests: Found pre request id 147119 for REQ: 147119
2015-01-30 15:21:08 INFO  Requests: Found pre request id 147125 for REQ: 147125
2015-01-30 15:21:10 INFO  Requests: Found pre request id 147131 for REQ: 147131
2015-01-30 15:21:11 INFO  Requests: Found pre request id 147135 for REQ: 147135
2015-01-30 15:21:13 INFO  Requests: Found pre request id 147137 for REQ: 147137
2015-01-30 15:21:17 INFO  Requests: Found pre request id 147138 for REQ: 147138
2015-01-30 15:21:18 INFO  Requests: Found pre request id 147144 for REQ: 147144
2015-01-30 15:21:18 INFO  Requests: Found pre request id 147145 for REQ: 147145
2015-01-30 15:21:18 INFO  Requests: Found pre request id 147147 for REQ: 147147
2015-01-30 15:21:18 INFO  Requests: Found pre request id 147148 for REQ: 147148
2015-01-30 15:21:18 INFO  Requests: Found pre request id 147150 for REQ: 147150
2015-01-30 15:21:18 INFO  Requests: Found pre request id 147151 for REQ: 147151
2015-01-30 15:21:18 INFO  Requests: Found pre request id 147158 for REQ: 147158
2015-01-30 15:21:18 INFO  Requests: Found pre request id 147161 for REQ: 147161
2015-01-30 15:21:18 INFO  Requests: Found pre request id 147164 for REQ: 147164
```

Worked nicely. No noticeable slowdowns.

**Comment by brookesy2** [comment]
Party on!! Thanks mate! :)

**Comment by Murodese** [comment]
Bonus, found a problem with release renaming that could cause postprocessing to crash. That might've been causing it.

**Comment by brookesy2** [comment]
Well, I have just slowed to a grinding halt, so maybe that didn't do it. Unless you just updated for that second crash? Hard to get stats on whats causing it as my terminal freezes completely :(

**Comment by brookesy2** [comment]
Is a mixture of postprocess and postgres. Let me jiggle a few things and see.

Last logline before it froze was:

2015-01-30 07:26:21 INFO tvrage: add online [The Kings Face E20 150128 HDTV H264 720p WITH]

**Comment by Murodese** [comment]
Ah, found it.

```
query = db.query(Release).filter(Release.category_id==int(category)).filter(
            (Release.files.any())|(Release.nfo_id!=None)|(Release.sfv_id!=None)|Release.pre_id!=None
        ).filter((Release.status!=1)|(Release.status==None))
```

Is missing parenthesis around Request.pre_id!=None, killing the query and making it try to load every single release. Should be fixed now.

**Comment by Murodese** [comment]
Hm, some upstart processes take way too long to start (I think prebot might be one of them). I'll need to investigate more.

**Comment by brookesy2** [comment]
Man, what a liability!!

I find prebot sometimes takes ages to connect to the server, unsure why though.

**Comment by Murodese** [comment]
I'm rewriting the daemonising stuff in another branch, so that should be more responsive at least. Hopefully with that change it won't hammer things quite so badly.

**Comment by brookesy2** [comment]
You are a gentleman and a scholar :)

Next for me is to add the web service request checking. Then to find out where the hell these all come from to see if I can replicate it.

**Pull request merged**
