### PR TITLE
Fix for prebot not starting

### PR DESCRIPTION
**Pull request by brookesy2**
I forgot to add the start to the daemon... I think I need my head checked!

### CODE REVIEW

**Comment by Murodese** [comment]
Start for zdaemon or the script itself? If the former, you probably want it to go at the end of the line in pynab.py instead.

**Comment by Murodese** [comment]
Incidentally, found where the reqid is being replaced - binaries.py:138. If there's a reqid but no name, the release name becomes the reqid - meaning that any release called something like 127525 or the like is a reqid. I'm going to chuck REQ: in front of that, so they become "REQ: 127525".

**Comment by brookesy2** [comment]
Was stat for zdaemon. It now mirrors the others.

Awesome news on the req. Hopefully get some time today. Been on site all
week, not much time! :(

**Comment by Murodese** [comment]
a.b.moovee contains a metric buttload of reqid releases when you're looking for something to test, as well. I've renamed them to REQ: [number], so you can just look for releases starting with that. That's only in the `mariadb` branch, though (which is fine to use even for postgre).

**Comment by brookesy2** [comment]
Will take a look see, hopefully can get some time this weekend! :)

Want to merge this request in? Otherwise people can't start the bot!

**Comment by brookesy2** [comment]
Legend! Now to wait for the REQ's from moovee to flow in :)

**Comment by Murodese** [comment]
Good news, there's 143,000 of them for you to test on :v

**Comment by brookesy2** [comment]
By the time im done there will probably be around 2m :p

**Comment by Murodese** [comment]
Haha. This is good, though! I wondered why I had so few movies compared to tv shows, and it's mostly because they're hidden in requests. Should get a lot more releases once it's done.

**Comment by brookesy2** [comment]
Don't hold your breath! I'm already worried as it is diving into someone else's code :)

After I attempt the req stuff from the db I should probably add some functions to utilize:

http://reqid.nzedb.com/index.php?reqid=404332&group=alt.binaries.inner-sanctum

**Pull request merged**
