### PR TITLE
Daemonize Prebot and add to pynab.py

### PR DESCRIPTION
**Pull request by brookesy2**
Added prebot to pynab.py. Unsure how logging works though, how are the log file names generated?

### CODE REVIEW

**Comment by Murodese** [comment]
It's based off the name of the calling script, but this will change soon because the current arrangement isn't able to differentiate between scanning and backfilling, for instance. I'll write and commit those changes tonight.

**Comment by Murodese** [comment]
Also, we can actually remove all the daemonisation in scripts - zdaemon handles all of it automatically.

**Comment by brookesy2** [comment]
Want me to cancel this PR and remove the daemonize function?

So a log file should be auto generated based off the calling file?

**Comment by brookesy2** [comment]
I guess also that the design decision here is to launch everything via pynab.py? I will update prebot.py to mirror how pubsub works :)

**Comment by brookesy2** [comment]
Removed daemonize. One thing I need to know more about, is how to have a log file generated for pres?

**Comment by Murodese** [comment]
pynab.py handles launching of long-running scripts and is generally an easy interface to add stuff to, so yeah.

I'm writing the logging stuff at the moment.

**Comment by Murodese** [comment]
Now that this is in, all you need to do is make sure that `log_init('pres')` is called at the start of your script.

**Comment by Murodese** [comment]
Oh, I actually already added it.

**Comment by Murodese** [comment]
Let me know when you're done and I'll merge it.

**Comment by brookesy2** [comment]
Ok, merged in your changes and added docopt as I saw the other scripts had it, thought I might as well try standardize.

**Comment by brookesy2** [comment]
Err hold that thought, just got this:

python3 pynab.py prebot
WARNING! zdrun is managing a different program!
our program   = ['python3', 'prebot.py', 'start']
daemon's args = ['python3', 'prebot.py']

**Comment by Murodese** [comment]
That'll happen if you update without stopping stuff. You need to find the process id and kill it manually.

**Comment by brookesy2** [comment]
Well I'll be, I was pretty sure I had, need new glasses :)

Only oddity is its not logging to the correct dir, other than that, works fine.

**Comment by Murodese** [comment]
Where's it logging to? I'm guessing your config.py still has logging_file in it instead of logging_dir (as per the new entry in config.sample.py)?

**Comment by brookesy2** [comment]
That is exactly it, perfecto!

**Comment by Murodese** [comment]
Hrm, it should be working anyway.

**Comment by Murodese** [comment]
All good, thanks! :)

All that's left is to associate the release and pre data :)

**Comment by brookesy2** [comment]
That is going to be a rather steep learning curve for me, but I am investigating :)

**Comment by Murodese** [comment]
You'll have to track and record req IDs as part of part processing, too. I originally had them included in Binary but took them out some time ago - once that's done, you just need to match the req ID to the ID in the db.

**Comment by brookesy2** [comment]
Wouldn't happen to have that old code laying around so I can take a look see? :)

**Comment by Murodese** [comment]
Actually, I guess it was never in a committed version. I removed it really early.

You can try taking a look at how newznab/nzedb do it (though the code is a bit nightmarish): 

https://github.com/nZEDb/nZEDb/blob/master/misc/update/decrypt_hashes.php
https://github.com/nZEDb/nZEDb/blob/master/nzedb/controllers/NameFixer.php

Keep in mind that pynab (optionally, but by default) deletes any releases that it can't get a good name for, so your db probably won't have any reqid releases in them. Something like `[214510]-[01/27] - "214510.par2" yEnc` that we can't get the name from either file or nfo will get marked as unwanted and deleted, so you may want to turn that option off while you test your new stuff (`delete_bad_releases`).

**Comment by brookesy2** [comment]
Will have a read. I guess the thing here is that if they are not being saved, will need to make modifications so that they are , as well as potentially have a column to contain the requestid? To allow post processing to look through all the pres to see if any match? As I assume we don't want to do this on the fly?

**Comment by Murodese** [comment]
Yeah, it's definitely a post-processing thing. Maybe as part of the normal release renaming procedure.

**Comment by Murodese** [comment]
I imagine it'd work something like this:

1) during release processing, check the release name for regex matching req id's (either store it in a separate field or parse it later from the name)
2) during rename, match the req id against the pre db, if it fails try to grab it from online sources

**Comment by brookesy2** [comment]
Just to cement this in my thick head, we are looking at releases.py and postprocessing.py. Modifications to releases.py to check if its a request, then store as an extra column in the db, or just keep the release and parse it out later. It may pay to use a separate column to assist in clearing out requests we can't match to a pre for at some point.

Modify postprocessing to add the ability to actually check the pre table for requests, potentially via some new requests.py class.

As always, thanks. You have some serious patience :) Now I just need to find the time!

**Comment by Murodese** [comment]
Yep, pretty much. It actually shouldn't be too difficult - you can add the pre-name checking stuff to the existing functions in releases.py (discover_name() from memory?) as a candidate and it'll use it if it's suitable. 

Split the request id off into its own column (but probably don't remove it from the release name itself until it's being completely renamed), postproc runs through the list of 8xxx (misc) releases and matches the reqid+group against the predb.

You'd also have to modify the unwanted release deletion to not delete releases with a reqid.

**Comment by brookesy2** [comment]
@Murodese So found a bit of an oddity. The bot no longer starts, just repeats the below over and over in logs. If I start manually via prebot.py start it logs correctly. I'm trying to figure out why, but no luck yet!

2015-01-22 17:35:16,946 - INFO - log: started pynab logger
2015-01-22 17:35:27,231 - INFO - log: started pynab logger
2015-01-22 17:35:37,517 - INFO - log: started pynab logger

**Comment by brookesy2** [comment]
Actually, this might just be my current setup, it seems scan is borked too.

**Comment by brookesy2** [comment]
Unfortunately I might have to admit defeat here! Could be beyond me.

Looking through the code it looks as if the discover_name() function is only called from a script and is used for ebooks/misc?

One thought was to leave the requests in the binaries table, during processing check for a release from the pre table and then add it to the releases table.

Other thought was just to add all requests to releases table and process them via post. Maybe have a cleanup method that would delete the request if not found in x months.

I can write the helper functions to find the stuff from the pre table, also the web services stuff to query the nzedb requests site, just can't put the pieces together! :( I will add the functions to a new requests.py.

I couldn't quite follow the process of binary to release. I have that feeling you get when you think you are close to understanding something but aren't quite sure!

**Comment by Murodese** [comment]
Discover_name is called by rename_bad_releases (the script), which is also called by postprocessing. Releases only really need to be renamed if they're in ebooks (whose regex allow un-named releases) or other-misc (where releases end up if they don't have a good name). Hence, anything that ends up in tv/movies/whatever has a "good enough" name, and doesn't really need renaming. Obfuscated releases or straight requests also end up in misc-other - up to now, they were deleted if they couldn't be renamed after grabbing file info. As of today, they stick around (so we can have a chance at renaming them).

Requests end up as normal releases, just in misc-other (because "REQ: 127203" isn't a proper name). Hence, we need to grab the ones out of misc-other and rename them (as part of discover_name).

Binary to release processing is pretty simple: a binary is an unfinished release, that may be missing parts or segments. So if we pick up 5/8 parts of something and binary processing is executed, it'll create a binary. However, that binary won't turn into a release until enough parts and segments are included to pass the completion check. Hence, metadata is pretty slim when stuff's a binary (really just stuff from usenet), but once it's turned into a release it goes through full postproc - password checking, sfv, nfo, tvrage, movie, etc. There's no point trying to rename stuff until it's a release (because if we do it earlier, we'd have to check the request id for every single segment and part that comes in).

**Comment by brookesy2** [comment]
Ok, that makes more sense on the discover_name function, as I was unsure how it was working. Thanks for that.

This is what im thinking, unsure if its right:

Add a get() function to requests.py that will simply split out the ID from the REQ then query the pre table to find if a REQ exists and return it to releases.py so it can follow along with the sfv, nfo etc. 

Optionally here another function could check the nzedb web service if none are found? Waiting for a web service may slow things down at that point I guess?  Maybe an additional postprocess step? Could treat it like imdb or tvrage I guess. Thoughts?

From there I am not to sure, that could be it? How does the release get a category? Reading through releases it looks like it relies on a combo of regex and group name. Should that be sufficient?

The info on binaries is very helpful also, thanks for breaking it down! Helps clear things up a bit :)

Again, thanks for your patience!

**Comment by Murodese** [comment]
Discover_name automatically gets a new category as part of the name selection process, so that's not a big issue. You basically just give it a release and it uses the available metadata to attempt to find a name, and then selects the best candidate from the list by running the name through categorisation - anything is better than misc-other, so it goes with that.

Yeah, if you're going to be running it against web services it should be set up like imdb/tvrage etc. What I'd do is run Pre post-proc and attach the Pre to the release, then leave discover_name to be called later on in postproc (basically where it is now). So, much like discover_name checks rar, sfv, nfo etc for names, it's now just additionally checking if Release.pre exists and if it does, adding that pre name into the candidate list in discover_name.

**Comment by brookesy2** [comment]
Blowing my feeble mind here :p

Essentially add another:

```python
                # grab and append sfv data to all releases
                if config.postprocess.get('process_sfvs', False):
                    threads.append(executor.submit(process_sfvs))
```

Which I can process and join pre id's to the requests.

From there discover_name would just take the id and get the name.

**Comment by Murodese** [comment]
Yup. In discover_name, you'd add something like:

```
if release.pre:
        potential_names += names_from_pre(release)
```

:)

**Comment by brookesy2** [comment]
Only took me like a week and a million comments to come to this conclusion :p

**Comment by Murodese** [comment]
That's working on an unfamiliar codebase for you :3

**Comment by brookesy2** [comment]
@Murodese Didn't make a pull request yet, but:

https://github.com/brookesy2/pynab/blob/3c15f60c28308f21efd11458efb41be24c144608/pynab/requests.py

I'm not exactly sure on query performance, so I did it in more of a bulk manner, instead of putting the pre query in a for loop. Does it matter? It will probably read cleaner in non bulk but didn't want to screw performance if so.

**Comment by Murodese** [comment]
Cool :)

The way you've done it is probably ok. It's a tradeoff of speed vs memory usage, basically: do it row by row and emit (n+1) queries, or do it how you have and only emit 2 queries. Since we're doing it as part of postproc, it's unlikely we'll ever run into a situation where there are too many IDs, particularly since they're already being limited by the first query. Should be fine :)

**Pull request merged**
